AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  stopstartinstance:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: stop_start_instance
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::569093484582:role/service-role/oimundo-role-ppfeb4o5'
      Runtime: python3.8
      Timeout: 3
